# ===----------------------------------------------------------------------=== #
# Copyright (c) 2026, Modular Inc. All rights reserved.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions:
# https://llvm.org/LICENSE.txt
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===----------------------------------------------------------------------=== #
from enum import Enum

import msgspec
from max.pipelines.core import TextContext
from max.pipelines.kv_cache import TransferReqData
from max.pipelines.modeling.types import RequestID


class SchedulerProgress(Enum):
    """Indicates whether a scheduler made progress during an iteration."""

    MADE_PROGRESS = "made_progress"
    NO_PROGRESS = "no_progress"


class PrefillRequest(
    msgspec.Struct, tag=True, omit_defaults=True, kw_only=True
):
    """A request for prefill (context encoding) processing.

    Contains the request ID, input context, and transfer engine details needed to
    process a prefill request through the pipeline and transfer KV cache data.
    """

    id: RequestID
    """Unique identifier for this request."""
    context: TextContext
    """The input context containing the request data and state."""
    transfer_engine_name: str
    """Name of the transfer engine to use for KV cache transfers."""
    dst_block_ids: list[int]
    """List of block IDs allocated for KV cache storage on Decode."""
    dst_replica_idx: int
    """The replica the request is on Decode."""


class PrefillResponse(
    msgspec.Struct, tag=True, omit_defaults=True, kw_only=True
):
    """A response for prefill (context encoding) processing.

    Contains the request ID and input context needed to run decode
    and generate tokens based on the prefill finished.
    """

    id: RequestID
    """Unique identifier for this request."""
    generated_token_id: int
    """The first generated token from prefill."""
    transfer_metadata: TransferReqData
    """The transfer metadata for the KV cache transfers."""
    draft_tokens: list[int] | None = None
    """Draft tokens generated by the Eagle/MTP draft model during prefill. When present, the decode node can feed these into its first speculative-decode iteration instead of starting with an empty draft cache."""


class CancelRequest(msgspec.Struct, tag=True, omit_defaults=True, kw_only=True):
    """A request to cancel an ongoing request.

    Used to signal that a specific request should be cancelled and its resources
    should be freed. This is typically used to cancel prefill or decode requests
    that are no longer needed.
    """

    id: RequestID
    """Unique identifier of the request to cancel."""
